# Generated by Django 4.0.3 on 2023-08-20 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
    ]
