# Generated by Django 4.0.3 on 2023-08-21 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_rename_author_blog_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author_id',
            new_name='author',
        ),
    ]
